#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${FIRESTORE_PROJECT_ID}" ]]; then
  echo "Missing FIRESTORE_PROJECT_ID environment variable" >&2
  exit 1
fi

if [[ -z "${FIRESTORE_LISTEN_ADDRESS}" ]]; then
  echo "Missing FIRESTORE_LISTEN_ADDRESS environment variable" >&2
  exit 1
fi

# Config gcloud project
gcloud config set project ${FIRESTORE_PROJECT_ID}

# Start emulator
gcloud beta emulators firestore start \
  --verbosity=debug \
  --log-http \
  --host-port=${FIRESTORE_LISTEN_ADDRESS} \