sudo: required

language: node_js
node_js:
  - "10"

services:
  - docker

env:
  - GIT_USERNAME=ddes-ci GIT_EMAIL=ci@ddes.io GOOGLE_APPLICATION_CREDENTIALS=/tmp/ci-auth.json

before_script:
  - scripts/google-token
  - docker-compose up --build -d dynamodb s3 firestore datastore
  - docker-compose ps

script:
  - scripts/build
  - scripts/test --runInBand

after_script:
  - docker-compose kill

after_success:
  - "[[ $TRAVIS_PULL_REQUEST != 'false' ]] && NODE_PATH=$NODE_PATH:support npx travis-deploy-once 'npx semantic-release-github-pr'"
  - NODE_PATH="$NODE_PATH:support" npx travis-deploy-once "npx semantic-release"
