nodeLinker: pnp

packageExtensions:
  pg-query-stream@*:
    dependencies:
      pg: "^8.7.3"
      "@types/pg": "^8.6.5"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
