version: '3.2'

services:
  dynamodb:
    image: socialpoint/dynalite
    command: dynalite --port=8000 --createTableMs=1 --deleteTableMs=1 --updateTableMs=100 --path=/var/dynamodb
    ports:
      - 8000:8000

  s3:
    image: skalar/fakes3
    command: s3rver --hostname 0.0.0.0 --port 5000 --directory /tmp/s3 --silent
    ports:
      - 5000:5000

  datastore:
    build: support/datastore
    environment:
      - DATASTORE_PROJECT_ID=ddes-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - '8081:8081'

  firestore:
    build: support/firestore
    environment:
      - FIRESTORE_PROJECT_ID=ddes-test
      - FIRESTORE_LISTEN_ADDRESS=0.0.0.0:8082
    ports:
      - '8082:8082'
