version: '3.2'

services:
  dynamodb:
    image: dlsniper/dynalite:1.2.0
    command: dynalite --port=8081 --createTableMs=1 --deleteTableMs=1 --updateTableMs=100 --path=/var/dynamodb
    ports:
      - 8081:8081

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: ddes
