#!/bin/bash

tsc=$PWD/node_modules/.bin/tsc
root=$PWD

rm -rf $root/packages/@ddes/core/dist
rm -rf $root/packages/@ddes/aws-store/dist
rm -rf $root/packages/@ddes/event-streaming/dist
rm -rf $root/packages/@ddes/aws-lambda-transformer/dist
rm -rf $root/packages/@ddes/store-transformations/dist
rm -rf $root/packages/@ddes/cli/dist
rm -rf $root/packages/@ddes/postgres-store/dist

if [[ $1 != "clean" ]]; then
  echo -n "building for node 10.. "
  cd $root/packages/@ddes/core && $tsc -p tsconfig.json
  cd $root/packages/@ddes/aws-store && $tsc -p tsconfig.json
  cd $root/packages/@ddes/event-streaming && $tsc -p tsconfig.json
  cd $root/packages/@ddes/aws-lambda-transformer && $tsc -p tsconfig.json
  cd $root/packages/@ddes/store-transformations && $tsc -p tsconfig.json
  cd $root/packages/@ddes/cli && $tsc -p tsconfig.json
  cd $root/packages/@ddes/postgres-store && $tsc -p tsconfig.json
  echo "done."
fi