#!/bin/bash

npx typedoc \
  --out ${1:-docs} \
  --name 'ddes' \
  --target ESNEXT \
  --exclude '**/+(tests|test-support)/**/*.ts' \
  --tsconfig tsconfig.typedoc.json \
  --readme none \
  --theme support/typedoc-theme \
  --mode modules \
  packages
