#!/bin/bash

set -e

jestArgs=()

while test $# -gt 0
do
  case "$1" in
    --tags)
      jestArgs+=("-t")
      jestArgs+=("\\[($(echo $2 | tr ',' '|'))\\]")      
      shift
      ;;
    *)
      jestArgs+=($1)
      ;;
  esac
  shift
done

jest=$PWD/node_modules/.bin/jest
export NODE_PATH="$NODE_PATH:$PWD/packages:$PWD/tests"

if [[ ! -z "$NODE" || ! -z "$CI" ]]; then
  nodeBin=${NODE:-node}
  nodeVersion=$($nodeBin -v)
  echo version $nodeVersion
  if $nodeBin node_modules/.bin/semver -r ">=8.10 <10" $nodeVersion; then
    export NODE_PATH="$NODE_PATH:$PWD/.transpiled-tests/node-8.10"
    jestArgs+=("--roots .transpiled-tests/node-8.10")
  elif $nodeBin node_modules/.bin/semver -r ">=10" $nodeVersion; then
    export NODE_PATH="$NODE_PATH:$PWD/.transpiled-tests/node-10"
    jestArgs+=("--roots .transpiled-tests/node-10")
  fi

  $nodeBin $jest ${jestArgs[*]}
else
  $jest --config ts-jest.config.json ${jestArgs[*]}
fi





