name: CI

on:
  push:
    branches:
      - master
    # Do not run on tags
    tags-ignore:
      - '*'
  pull_request:
    # Run on to branches with an open PR
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@skalar'
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: yarn install
        run: yarn install
        env:
          CI: true
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Setup services
        run: docker-compose up --build -d
      - name: Test
        run: yarn test
        env:
          CI: true
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Teardown
        run: docker-compose kill
